# Generated by Django 5.2.16 on 2026-07-08 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_city', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Eldoret', 'Eldoret')], default='Nairobi', max_length=50)),
                ('agency_role', models.CharField(choices=[('Urban Planner', 'Urban Planner'), ('Law Enforcement', 'Law Enforcement'), ('Researcher', 'Researcher'), ('Administrator', 'Administrator')], default='Urban Planner', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
