# Generated by Django 5.2.16 on 2026-07-24 18:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_zone_alter_incident_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('infra_type', models.CharField(choices=[('Road', 'Road'), ('Hospital', 'Hospital'), ('School', 'School'), ('Power', 'Power'), ('Water', 'Water'), ('Other', 'Other')], max_length=50)),
                ('city', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Eldoret', 'Eldoret')], default='Nairobi', max_length=50)),
                ('status', models.CharField(default='Operational', max_length=50)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-reported_at']},
        ),
        migrations.RemoveField(
            model_name='incident',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='planningproject',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='planningproject',
            name='priority',
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.zone'),
        ),
        migrations.AddField(
            model_name='incident',
            name='reported_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='planningproject',
            name='planner_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planningproject',
            name='project_type',
            field=models.CharField(choices=[('Road', 'Road'), ('Hospital', 'Hospital'), ('School', 'School'), ('Mall', 'Mall'), ('Residential', 'Residential')], default='Road', max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='api.zone'),
        ),
        migrations.AlterField(
            model_name='planningproject',
            name='stage',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='planningproject',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ImpactPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffic_impact', models.CharField(blank=True, max_length=100)),
                ('crime_risk_delta', models.CharField(blank=True, max_length=100)),
                ('population_shift', models.CharField(blank=True, max_length=100)),
                ('economic_activity', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_predictions', to='api.planningproject')),
            ],
        ),
        migrations.CreateModel(
            name='PopulationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('population', models.IntegerField()),
                ('density', models.FloatField(blank=True, help_text='People per square km', null=True)),
                ('growth_rate', models.FloatField(blank=True, help_text='Percentage growth since last record', null=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='population_records', to='api.zone')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('zone', 'year')},
            },
        ),
    ]
