# Generated by Django 5.2.16 on 2026-08-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_infrastructure_alter_incident_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='agency_role',
            field=models.CharField(choices=[('Urban Planner', 'Urban Planner'), ('Law Enforcement', 'Law Enforcement'), ('Crime Analyst', 'Crime Analyst'), ('Researcher', 'Researcher'), ('Administrator', 'Administrator')], default='Urban Planner', max_length=50),
        ),
    ]
